Repository aaahyunseo/mju-sw-competition-project, pull requests merged in 2024-08, with the labels that each got.

#2 Feature/#1 Spring Initializer init
  .gitignore
  .gitmessage.txt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/swcompetitionproject/SwCompetitionProjectApplication.java
  src/test/java/com/example/swcompetitionproject/SwCompetitionProjectApplicationTests.java
Labels: good first issue

#4 Feature/#3 엔티티 생성
  src/main/java/com/example/swcompetitionproject/entity/BaseEntity.java
  src/main/java/com/example/swcompetitionproject/entity/Board.java
  src/main/java/com/example/swcompetitionproject/entity/ChattingRoom.java
  src/main/java/com/example/swcompetitionproject/entity/Message.java
  src/main/java/com/example/swcompetitionproject/entity/RoomMember.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
Labels: enhancement

#8 Feature/#7 Repository 생성
  src/main/java/com/example/swcompetitionproject/repository/BoardRepository.java
  src/main/java/com/example/swcompetitionproject/repository/ChattingRoomRepository.java
  src/main/java/com/example/swcompetitionproject/repository/MessageRepository.java
  src/main/java/com/example/swcompetitionproject/repository/RoomMemberRepository.java
  src/main/java/com/example/swcompetitionproject/repository/UserRepository.java
Labels: enhancement

#10 Feature/#5 예외 처리를 위한 exeption 작성
  src/main/java/com/example/swcompetitionproject/exception/ConflictException.java
  src/main/java/com/example/swcompetitionproject/exception/CustomException.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/exception/ForbiddenException.java
  src/main/java/com/example/swcompetitionproject/exception/NotFoundException.java
  src/main/java/com/example/swcompetitionproject/exception/UnauthorizedException.java
  src/main/java/com/example/swcompetitionproject/exception/controller/ExceptionController.java
  src/main/java/com/example/swcompetitionproject/exception/dto/ErrorResponseDto.java
Labels: enhancement

#11 Feature/#6 Athentication 추가
  src/main/java/com/example/swcompetitionproject/authentication/AuthenticatedUser.java
  src/main/java/com/example/swcompetitionproject/authentication/AuthenticatedUserArgumentResolver.java
  src/main/java/com/example/swcompetitionproject/authentication/AuthenticationContext.java
  src/main/java/com/example/swcompetitionproject/authentication/AuthenticationExtractor.java
  src/main/java/com/example/swcompetitionproject/authentication/AuthenticationInterceptor.java
  src/main/java/com/example/swcompetitionproject/authentication/JwtEncoder.java
  src/main/java/com/example/swcompetitionproject/authentication/JwtTokenProvider.java
  src/main/java/com/example/swcompetitionproject/exception/CustomException.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/exception/UnauthorizedException.java
Labels: enhancement

#14 Feature/#12 Exception 파일 추가
  src/main/java/com/example/swcompetitionproject/exception/BadRequestException.java
  src/main/java/com/example/swcompetitionproject/exception/DtoValidationException.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
Labels: enhancement

#13 Feature/#9 Config 설정
  src/main/java/com/example/swcompetitionproject/config/AuthenticationConfig.java
  src/main/java/com/example/swcompetitionproject/config/CorsConfig.java
Labels: enhancement

#21 Feature/#19 배포 작업
  Dockerfile
  src/main/java/controller/TestController.java
Labels: enhancement

#20 Feature/#16 명지대 통합로그인 사이트를 통해서 로그인
  src/main/java/com/example/swcompetitionproject/SwCompetitionProjectApplication.java
  src/main/java/com/example/swcompetitionproject/config/RestTemplateConfig.java
  src/main/java/com/example/swcompetitionproject/controller/AuthController.java
  src/main/java/com/example/swcompetitionproject/dto/request/LoginDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/TokenResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/BaseEntity.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/repository/UserRepository.java
  src/main/java/com/example/swcompetitionproject/service/LoginService.java
Labels: enhancement

#23 Feature/#22 마이페이지에 이름 등록
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/ModifyUserNameDto.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/exception/controller/ExceptionController.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#27 Hotfix/#26 테스트 버그 수정
  src/main/java/com/example/swcompetitionproject/controller/TestController.java
  src/main/java/com/example/swcompetitionproject/exception/controller/ExceptionController.java
Labels: bug

#29 Feature/#28 로그인 완료 시 AccessToken결과에 나오도록 수정
  src/main/java/com/example/swcompetitionproject/controller/AuthController.java
  src/main/java/com/example/swcompetitionproject/dto/response/LoginResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
Labels: enhancement

#32 Feature/#31CI/CD
  .github/workflows/gradle.yml
Labels: enhancement

#33 Feature/#24 사용자 인포 조회하는 API
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/user/ModifyUserNameDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/user/UserResponseDto.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#35 Feature/#34 마이페이지에서 내가 작성한 게시판 조회하는 API
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/MyBoardListData.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/MyBoardResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/repository/BoardRepository.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#38 Feature/#37 메인페이지 기능 개발
  src/main/java/com/example/swcompetitionproject/controller/MainPageController.java
  src/main/java/com/example/swcompetitionproject/dto/response/mainpage/MainPageResponseData.java
  src/main/java/com/example/swcompetitionproject/repository/BoardRepository.java
  src/main/java/com/example/swcompetitionproject/service/MainPageService.java
Labels: enhancement

#40 Feature/#39 게시글 수정 로직 변경
  src/main/java/com/example/swcompetitionproject/dto/request/board/UpdateBoardDto.java
  src/main/java/com/example/swcompetitionproject/entity/Board.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
Labels: enhancement

#42 Feature/#41 게시글 카테고리 로직 추가
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardData.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
Labels: enhancement

#44 Feature/#43 나의 게시판 조회시 Dormitory도 나오게 변경
  src/main/java/com/example/swcompetitionproject/dto/response/board/MyBoardResponseDto.java
Labels: enhancement

#47 Feature/#25 마이페이지에 카테고리 추가하는 API
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/user/CreateUserCategoryDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardData.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/Category.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/repository/CategoryRepository.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#49 Feature/#45 마이페이지에 카테고리 삭제하는 API
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#51 마이페이지에 카테고리 전체 조회는 API
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/response/category/CategoryListData.java
  src/main/java/com/example/swcompetitionproject/dto/response/category/CategoryResponseDto.java
  src/main/java/com/example/swcompetitionproject/repository/CategoryRepository.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#50 게시글 카테고리 리스트 반환 로직 수정
  src/main/java/com/example/swcompetitionproject/controller/BoardController.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardData.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/Board.java
  src/main/java/com/example/swcompetitionproject/entity/BoardCategory.java
  src/main/java/com/example/swcompetitionproject/entity/Category.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/repository/UserRepository.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
Labels: enhancement

#54 Fix/53 카테고리 삭제시 유저 검증 로직 추가
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/repository/CategoryRepository.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: bug

#56 Feat/#55 코드 정렬
  src/main/java/com/example/swcompetitionproject/config/CorsConfig.java
  src/main/java/com/example/swcompetitionproject/controller/AuthController.java
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/controller/TestController.java
  src/main/java/com/example/swcompetitionproject/dto/request/auth/LoginDto.java
  src/main/java/com/example/swcompetitionproject/dto/request/board/CreateBoardDto.java
  src/main/java/com/example/swcompetitionproject/dto/request/user/ModifyUserNameDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/MyBoardResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/category/CategoryResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/chatting/ChattingRoomListDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/user/UserResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/Category.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/exception/BadRequestException.java
  src/main/java/com/example/swcompetitionproject/exception/ConflictException.java
  src/main/java/com/example/swcompetitionproject/exception/CustomException.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/exception/NotFoundException.java
  src/main/java/com/example/swcompetitionproject/exception/UnauthorizedException.java
  src/main/java/com/example/swcompetitionproject/exception/ValidationException.java
  src/main/java/com/example/swcompetitionproject/exception/controller/ExceptionController.java
  src/main/java/com/example/swcompetitionproject/repository/BoardRepository.java
  src/main/java/com/example/swcompetitionproject/repository/CategoryRepository.java
  src/main/java/com/example/swcompetitionproject/service/LoginService.java
  src/main/java/com/example/swcompetitionproject/service/MainPageService.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#57 Feature/#52 채팅 기능 수정
  src/main/java/com/example/swcompetitionproject/config/StompWebSocketConfig.java
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/chatting/ChatMessageDto.java
  src/main/java/com/example/swcompetitionproject/entity/ChattingRoom.java
  src/main/java/com/example/swcompetitionproject/entity/RoomMember.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/repository/MessageRepository.java
  src/main/java/com/example/swcompetitionproject/repository/RoomMemberRepository.java
  src/main/java/com/example/swcompetitionproject/repository/UserRoomRepository.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
Labels: enhancement

#59 Feature/#58 마이페이지에서 성별 정보 받는 기능 추가
  src/main/java/com/example/swcompetitionproject/controller/BoardController.java
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/user/ModifyUserInfoDto.java
  src/main/java/com/example/swcompetitionproject/dto/request/user/UserInfoDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/user/UserResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/GenderType.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#63 Feature/#62 마이페이지 정보 조회 성별 추가
  src/main/java/com/example/swcompetitionproject/config/StompWebSocketConfig.java
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
Labels: enhancement

#65 Feature/#64 게시글 좋아요 기능
  src/main/java/com/example/swcompetitionproject/controller/BoardController.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardListData.java
  src/main/java/com/example/swcompetitionproject/entity/Board.java
  src/main/java/com/example/swcompetitionproject/entity/Interest.java
  src/main/java/com/example/swcompetitionproject/entity/User.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/repository/InterestRepository.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
Labels: enhancement

#66 feat: 채팅 연결 성공 - #64
  src/main/java/com/example/swcompetitionproject/config/StompWebSocketConfig.java
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
Labels: enhancement

#69 Feature/#68 마이페이지에서 카테고리&게시판 정렬
  src/main/java/com/example/swcompetitionproject/repository/BoardRepository.java
  src/main/java/com/example/swcompetitionproject/repository/CategoryRepository.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#71 Feaure/#70 마이페이지에서 카테고리와 게시판 정렬 바뀜
  src/main/java/com/example/swcompetitionproject/repository/BoardRepository.java
  src/main/java/com/example/swcompetitionproject/repository/CategoryRepository.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#73 Bog/#72 게시판 수정시 카테고리 반영
  src/main/java/com/example/swcompetitionproject/controller/BoardController.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
Labels: enhancement

#74 Refactor/#61 로그인&로그아웃 리팩토링
  src/main/java/com/example/swcompetitionproject/controller/AuthController.java
  src/main/java/com/example/swcompetitionproject/service/LoginService.java
Labels: refactor

#67 Feature/#60 채팅 기능 연결 작업
  src/main/java/com/example/swcompetitionproject/controller/AuthController.java
  src/main/java/com/example/swcompetitionproject/controller/BoardController.java
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/controller/ChattingRoomController.java
  src/main/java/com/example/swcompetitionproject/dto/request/board/RoomIdDto.java
  src/main/java/com/example/swcompetitionproject/dto/request/chatting/ChatMessageDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/auth/LoginResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/auth/TokenResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardData.java
  src/main/java/com/example/swcompetitionproject/dto/response/board/BoardDetailResponseDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/chatting/ChattingRoomListData.java
  src/main/java/com/example/swcompetitionproject/dto/response/chatting/ChattingRoomListDto.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
  src/main/java/com/example/swcompetitionproject/service/LoginService.java
Labels: enhancement

#76 Hotfix/#75 버그 수정
  src/main/java/com/example/swcompetitionproject/controller/AuthController.java
Labels: bug

#78 충돌 해결
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
Labels: bug

#80 Feature/#79 채팅방 퇴장 기능 수정
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/repository/UserRepository.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#83 Feature/#82 채팅 입장, 퇴장 메세지 수정
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
Labels: enhancement

#85 Feature/#84 예외처리 수정
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
Labels: enhancement

#86 Feature/#81 목록 인원 가득 찬거 맨 아래로
  src/main/java/com/example/swcompetitionproject/repository/ChattingRoomRepository.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
Labels: enhancement

#89 Feature/#88 기숙사 최대 인원 입력 예외처리
  src/main/java/com/example/swcompetitionproject/exception/BadRequestException.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
Labels: bug, enhancement

#92 Feature/#87 채팅방에서 프로필 조회
  src/main/java/com/example/swcompetitionproject/controller/MypageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/user/UserProfileDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/user/UserProfileResponseDto.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: enhancement

#94 Feature/#93 채팅 기능 입장 오류 수정
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
Labels: bug, enhancement

#96 Feature/#95 게시글 작성 시 성별 판별하기
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/exception/ErrorCode.java
  src/main/java/com/example/swcompetitionproject/service/BoardService.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
Labels: enhancement

#98 Feature/#97 이름 변경 시 채팅 오류 해결
  src/main/java/com/example/swcompetitionproject/controller/ChatMessageController.java
  src/main/java/com/example/swcompetitionproject/dto/request/chatting/ChatMessageDto.java
  src/main/java/com/example/swcompetitionproject/dto/response/user/UserResponseDto.java
  src/main/java/com/example/swcompetitionproject/entity/Message.java
  src/main/java/com/example/swcompetitionproject/service/ChattingService.java
  src/main/java/com/example/swcompetitionproject/service/MyPageService.java
Labels: bug, enhancement
